config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users

  delete :logout, to: 'sessions#destroy'

  resources :users do
    resources :projects do
      patch :update_inline, on: :member
      resources :tasks do
        patch :update_task_inline, on: :member
      end
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :title, :description, presence: true

  def formatted_created_at
    created_at.strftime("%Y-%m-%d %H:%M:%S")
  end
end

app/models/task.rb
class Task < ApplicationRecord
  enum status: [:created, :in_progress, :done]

  belongs_to :project

  default_scope { order(priority: :desc) }
  scope :created, -> { where(status: 0) }
  scope :in_progress, -> { where(status: 1) }
  scope :done, -> { where(status: 2) }

  validates :body, :task_name, presence: true

  def dead?
    Time.now > deadline
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects, dependent: :destroy

  validates :first_name, :last_name, :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_projects, only: %i[index update_inline]
  before_action :authenticate_user!

  def index
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @user = current_user
    @project = @user.projects.new
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      redirect_to user_project_path(current_user, @project), flash: { success: 'Project was added! '}
    else
      render :new, flash: { alert: 'Some errors occured'}
    end
  end

  def edit
    @user = current_user
    @project = @user.projects.find(params[:id])
  end

  def update
    @project = current_user.projects.find(params[:id])
    if @project.update(project_params)
      redirect_to user_projects_path(@project), flash: { success: 'project was updated! '}
    else
      render :edit
    end
  end

  def update_inline
    @project = current_user.projects.find(params[:id])
    if @project.update(project_params)
      redirect_to user_projects_path, flash: { success: 'project was updated! '}
    else
      render :index
    end
  end

  def destroy
    @project = current_user.projects.find(params[:id])
    @project.destroy
    redirect_to user_projects_path, flash: { success: 'Project was deleted! '}
  end

  private

  def set_projects
    @projects = current_user.projects
  end

  def project_params
    params.require(:project).permit(:title, :description)
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_project

  def index
    @tasks = @project.tasks
  end

  def show
    @task = @project.tasks.find_by(params[:id])
  end

  def new
    @task = @project.tasks.new
  end

  def create
    @task = @project.tasks.build(task_params)
    if @task.save
      redirect_to user_project_path(current_user, @project), flash: { success: 'Task was created! '}
    else
      render :new#, flash: { alert: 'Some errors occured'}
    end
  end

  def edit
    @user = current_user
    @task = @project.tasks.find(params[:id])
  end

  def update
    @task = @project.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to user_project_path(current_user, @project), flash: { success: 'Task was created! '}
    else
      render :edit
    end
  end

  def update_task_inline
    @task = @project.tasks.find(params[:id])
    #@task.update!(task_params)
    if @task.update(task_params)
      redirect_to user_project_path(current_user, @project), flash: { success: 'Task was created! '}
    else
      render :index
    end
  end

  def destroy
    @project = current_user.projects.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    @task.destroy
    redirect_to user_project_path(current_user, @project), flash: { success: 'task was deleted! '}
  end

  private

  def find_project
    @project = current_user.projects.find(params[:project_id])
  end

  def task_params
    params.require(:task).permit(:task_name, :body, :status, :deadline, :priority)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %w[show edit update destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to users_path, flash: { success: 'User successfully created!' }
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), flash: { success: "User successfully updated!."}
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, flash: { success: 'User deleted.' }
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>

    <div class="container">

      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form_inline.html.erb
<%= form_with model: [current_user, project],
              url: update_inline_user_project_path(current_user, project),
              local: true,
              class: 'form-inline',
              html: {style: 'display: block'},
              data: { project_id: project.id } do |form| %>
  <%= render 'shared/errors', resource: project %>
  <%= form.text_field :title, class: 'form-control mr-2' %>
  <%= form.text_area :description, class: 'form-control mr-2' %>

  <%= form.submit 'OK', class: 'btn btn-primary' %>
<% end %>

app/views/projects/_form_task_inline.html.erb
<%= form_with model: [current_user, @project, task],
              url: update_task_inline_user_project_task_path(current_user, @project, task),
              local: true,
              class: 'form-inline',
              html: {style: 'display: block'},
              data: { task_id: task.id } do |form| %>
  <%# render 'shared/errors', resource: task %>

  <div class="container mb-2" style="display: flex">
    <div class="flex-column mb-3 text-center"><%= form.label :status, class: 'form-label', style: 'mr-3' %>:
    <%= form.text_field :status, :size=>'11', class: 'form-control' %></div>
    <div class="flex-column mb-3 text-center field_with_errors"><%= form.label :priority, class: 'form-label mr-3' %>:
      <%= form.text_field :priority, class: 'form-control' %></div>
    <div class="flex-column mb-3 text-center"><%= form.label :deadline, class: 'form-label mr-3' %>:
    <%= form.date_field :deadline, class: 'form-control' %></div>

    <%# form.text_area :description, class: 'form-control mr-2' %>

  <%= form.submit 'OK', class: 'btn btn-secondary mt-3' %></div>
<% end %>

app/views/projects/edit.html.erb
<%= render 'form' %>
<%= link_to 'Back to projects', user_projects_path, class: 'btn btn-primary' %>

app/views/projects/index.html.erb
<h1 class="mb-4">My projects</h1>

  <% if current_user.projects.any? %>
  <% current_user.projects.each do |project| %>
    <article class="card mb-3">
      <div class="card-body">
      <h4 class="text-center"><%= project.title %></h4>

        <div class='but'><div class="render-edit-project-<%= project.id %>" style="display: none"><%= render 'form_inline', project: project %></div></div>

      <section class="card-text">
        <time datetime="<%= project.formatted_created_at %>">
          <small><%= project.formatted_created_at %></small>
        </time>
        <p class="my-2"><%= project.description %></p>

      </section>
       <%= link_to 'Show', user_project_path(project.user_id, project.id), class: 'btn btn-primary' %>
       <%= link_to 'Edit', edit_user_project_path(project.user_id, project.id), class: 'btn btn-warning' %>

       <%# button_to 'Destroy', user_project_path(project.user_id, project), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?'}, remote: true %>
      </div>
    </article>
    <% end %>
  <% else %>
    <h2> You haven't projects now. </h2>
    <%= link_to "Create new project", new_user_project_path, class: 'btn btn-primary' %>
  </div>

<% end %>
<hr>
<%= link_to "Create new project", new_user_project_path, class: 'btn btn-primary m-53' %>

app/views/projects/show.html.erb
<h3 class="mb-4" xmlns="http://www.w3.org/1999/html">My projects - Project show</h3>

<article class="card">
  <h5><%= @project.title %>
  <button class="hide-project-desc btn btn-success btn-sm">show/hide description</button></h5>
  <div class="card-header">
    <p class="card card-header"><%= @project.description %></p>
    <p class="mb-2" style="font-size: smaller">Created at: <%= @project.formatted_created_at %></p>
  </div>

  <table class="table caption-top" style="font-size: 0.9rem">
    <caption>Tasks in this project</caption>
    <thead>
    <th class="table-condensed" style="text-align: center">Created tasks:</th>
    <th class="table-condensed" style="text-align: center">In progress</th>
    <th class="table-condensed" style="text-align: center">Done!</th>
    </thead>
    <td><% @project.tasks.created.each do |task| %>
        <div class="card border-1 border-dark mb-3">
          <table class="table table-bordered table-danger" style="width: 100%">
            <td id="tb-created"><%= task.body %></td>
            <%= render 'projects/form_task_inline', task: task %>
            <%= link_to 'Edit', edit_user_project_task_path(current_user, @project, task), class: 'btn btn-danger mb-3 small' %>
          </table>
        </div>

    <% end %>
  </td>
  <td>
    <% @project.tasks.in_progress.each do |task| %>
      <div class="card border-1 border-dark mb-3">
        <table class="table table-bordered table-warning" style="width: 100%">
          <td><%= task.body %></td>
          <%= render 'projects/form_task_inline', task: task %>
          <%= link_to 'Edit', edit_user_project_task_path(current_user, @project, task), class: 'btn btn-warning mb-3 small' %>
        </table>
      </div>
  <% end %>
  </td><td>
    <% @project.tasks.done.each do |task| %>
      <div class="card border-1 border-dark mb-3">
        <table class="table table-bordered table-success" style="width: 100%">
          <td><%= task.body %></td>
          <%= render 'projects/form_task_inline', task: task %>
          <%= link_to 'Edit', edit_user_project_task_path(current_user, @project, task), class: 'btn btn-success mb-3 small' %>
          <%= link_to 'Delete', user_project_task_path(current_user, @project, task), class: 'btn btn-danger mb-3 small',
                      method: :delete, data: { confirm: 'Are you sure? Task will be deleted!'} %>

        </table>
      </div>
    <% end %>
  </table>
  <%= link_to 'Create new task', new_user_project_task_path(current_user, @project), class: 'btn btn-warning mb-3' %>
  <%= link_to 'Back to Projects', user_projects_path, class: 'btn btn-primary mb-3' %>
  <%= button_to 'Destroy this project', user_project_path(@project.user_id, @project), class: 'btn btn-danger',
                method: :delete, data: { confirm: 'Are you sure? All task will be deleted!'}, remote: true %>
        <%# link_to 'Edit', user_edit_project_path(@project.user_id, @project), class: 'btn btn-secondary' %>
        <%# link_to 'Destroy', user_project_path(@project.user_id, project), class: 'btn btn-danger',
          data: {method: :delete, confirm: 'Are you sure?'} %>
  </div></div>
  </div>
</article>
<script>
  let projButton = document.querySelector('.hide-project-desc');
  let projectDesc = document.querySelector('.card-header');

  projButton.onclick = function toggle() {
    projectDesc.style.display = (projectDesc.style.display == 'none') ? '' : 'none'
  };
</script>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <div>
    <h2>Errors count:<%=  resource.errors.count %></h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= flash[:alert] = "#{message}" %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light" style="background-color: #999999;">
  <div class="container">
    <div class="navbar-header">
      <% if user_signed_in? && current_user.present? %>
          <%= link_to 'My ToDo list', user_projects_path(current_user), class: 'navbar-brand' %>
          <%= link_to 'Create new project', new_user_project_path(current_user), class: 'navbar-brand' %>
      <% else %>
        <%= link_to 'About', root_path, class: 'navbar-brand' %>
      <% end %>
    </div>
    <div id="navbar">
      <ul class="navbar-btn navbar-link">
          <% if user_signed_in? && current_user.present? %>
            <%= link_to "#{current_user.email}", user_path(current_user) %>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
          <% else %>
            <li><%= link_to 'Log In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </ul>

    </div>
  </div>
</nav>

app/views/tasks/_form.html.erb
<%= form_with model: [current_user, @project, @task] do |f| %>
  <%= render 'shared/errors', resource: @task %>
  <h3>Create new task:</h3>
  <div class="mb-3 mt-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :task_name %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :task_name, class: 'form-control' %>
    </div>

    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>
    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>

    <div class="col-sm-2 col-form-label">
      <%= f.label :status %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :status, class: 'form-control' %>
    </div>

    <div class="col-sm-2 col-form-label">
      <%= f.label :priority %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :priority, class: 'form-control' %>
    </div>

    <div class="col-sm-2 col-form-label">
      <%= f.label :deadline %>
    </div>
    <div class="col-sm-10">
      <%= f.date_field :deadline, class: 'form-control' %>
    </div>

    <%= f.submit 'Submit project!', class: 'btn btn-primary mt-3' %>

  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>
<%= button_to 'Back to project', user_projects_path, class: 'btn btn-primary' %>

app/views/tasks/index.html.erb
<h2 class="container" style="align-content: center">Tasks of project: <%= @project.title %></h2>

app/views/tasks/new.html.erb
<%= render 'form' %>
<%# link_to 'Back to projects', user_projects_path, class: 'btn btn-primary' %>

app/views/users/index.html.erb
<h2>List of users</h2>
<% @users.each do |user| %>
  <p><%= user.first_name + ' ' + user.last_name%></p>
  <p><%=  %></p>
  <p><%= user.email %></p>
  <p><%= user.created_at %></p>
<% end %>

app/views/users/show.html.erb
<h1>My projects - Users show</h1>

<% if @user.projects.any? %>
  <% @user.projects.each do |project| %>
    <article class="card mb-3">
      <div class="card card-header">
        <h4><%= project.title %></h4>
      </div>
      <div class="card card-body">
        <%= project.description %>
      </div>
    </article>

  <% end %>
<% else %>
  <h2> You haven't projects now. </h2>
  <%= link_to "Create new project", new_user_project_path(@user), class: 'btn btn-warning' %>
<% end %>

app/views/welcome/index.html.erb
<!doctype html>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title> My todo list app </title>


</head>
<body>
  <div class="container" style="align-content: center">
    <h2 style="text-align: center">To-Do List App</h2>
    <h4 class="want-task-flow mb-4" style="opacity: 70%; font-style: italic;">
      <li>If you want to manage your tasks and projects more effectively - this app helps in controlling your task-flow.</li>
      <li>You can create your own projects and tasks after <%= link_to "Sign Up", new_user_registration_path %></li>
    </h4>
    <figure style="align-items: center">
      <img src="after_sign.png" height="auto" width="960px" alt="After sign up.">
      <figcaption>After sign up you can create your own projects and tasks</figcaption>
    </figure>
    <h4 class="mb-4" style="opacity: 70%; font-style: italic;">
      <li>In project you can create tasks, for example task list view:</li>
    </h4>
    <h5><li>task list grouped in three columns, as 'created', 'in_progress' and 'done' statuses</li></h5>
    <h5><li>you can set task priority by number, and tasks views by order its priority</li></h5>
      <figure style="align-items: center">
      <img src="show_project.png" height="auto" width="960px" alt="Show project.">
      <figcaption>After sign up you can create your own projects and tasks</figcaption>
    </figure>




  </div>


</body>
</html>